### ISSUE TITLE
How to trace ES6 Code call stack

### ISSUE THREAD

**Issue by arindam89** [ValYouW/njsTrace#14]
I am interested in seeing how the callstack of my express app looks like, but when I plugged njstrace there, I am not getting any trace, but for my local modules, it is working. 

How to use for a full-fledged application.

**Comment by arindam89** [comment]
My bad, with this config, I am getting it,

```
const njstrace = require("njstrace").inject({ files: ["**/*.js"] });
```

**Comment by arindam89** [comment]
But it doesn't work for ES6 syntax,

```
function intToStr(i) {
  if (i < 10) return i + "";
  else return intToStr(Math.floor(i / 10)) + (i % 10);
}

const respond = (req, res) => res.send("Hello World!");

module.exports = {
  intToStr,
  respond
};

```

Here, `respond` wont be logged.

**Comment by ValYouW** [comment]
Thats a knows issue, reported on #12
