### ISSUE TITLE
Tracing Node's core modules?

### ISSUE THREAD

**Issue by christophschw** [ValYouW/njsTrace#18]
Hey, me again ;)

I wonder if it would be possible to trace Node's core modules like `fs` or `util`. I know that this is a very unusual demand but it would me help to detect anomalies during malicious behavior in Node apps.
Since the source modules are implemented in Javascript, I thought it should be possible to extend the code with njsTrace, no?
https://github.com/nodejs/node/tree/master/lib
But I suppose that this not that trivial since core modules won't processed by `Module._compiled`, right?
Maybe, we could use the (deprecated) `natives` module in order to fetch and manipulate the source code of the core modules. What do you think?

Do you have any hints in order to meet this requirement?
Have a nice weekend & thanks again!

**Comment by ValYouW** [comment]
Hi!

Hmmm, this is not possible I'm afraid, at least not something I know of....
I went to check a bit on how these files are being used, and if I understood correctly, during build time (of node.exe) there is a script (`tools/js2c.py`) that embed all internal javascript code inside a c++ file (`node_javascript.cc`) that is then linked into node. Then inside `node_native_module.cc` they are being compiled (at runtime, method: `LookupAndCompile`), which means we can't touch this...

What you can do is "hijack" all the functions inside these modules and "trace" them, say you want to hikack `fs`, then after calling `njsTrace.inject` do this:
```js
function wrapFunc(module, file, fname) {
	var orig = module[fname];
	module[fname] = function() {
		// note we dont really have line numbers for this method, use 0
		var __njsEntryData__ = __njsTraceEntry__({ file: file, name: fname, line: '0', args: arguments });
		var res = orig.apply(fs, arguments);
		__njsTraceExit__({ entryData: __njsEntryData__, exception: false, line: '0', returnValue: res });
		return res;
	}
}

var fs = require('fs');
var fsFuncs = Object.getOwnPropertyNames(fs).filter(x => typeof (fs[x]) === 'function');
for (let i = 0; i < fsFuncs.length; i++) {
	wrapFunc(fs, 'fs.js', fsFuncs[i]);
}
```

But since this is too "dangerous" I don't think it should be part of this library... try the above method and keep me posted, it's interesting :)

**Comment by christophschw** [comment]
Hey, thank you again for the explanation and especially for the code! That's my understanding too from what I read how Node handles the core modules.

The code is working flawlessly when I use `fs` in the scope of the function above. The problem is that I would like to trace `fs` (as well as other core modules) globally. Consider following malicious code injection: `res.end(require('fs').readdirSync('.').toString())`([Source](https://nodegoat.herokuapp.com/tutorial/a1)). This is what I'd like to see in the traces.
What about to make this global in `NJSTrace.prototype.setGlobalFunction` for example? That should work out or do I have a mistake?

What I tried in the meantime was to overwrite the core modules with local modules:
```
'use strict';
var Module = require('module');
var assert = require('assert');

var require = function require(path) {
    assert(typeof (path) == 'string', 'path must be a string');
    assert(path, 'missing path');

    var _this = this;
    var next = function () { return Module.prototype.require.next.apply(_this, arguments); };

    switch (path) {
        case 'util':
            return require('./src/util.js')

        default:
            // forward unrecognized modules to previous handler
            //console.log(path);
            return next(path);
    }
};

require.next = Module.prototype.require;
Module.prototype.require = require;
module.exports = {}
```
[Source](https://stackoverflow.com/questions/26926282/how-to-override-node-js-core-module) 

In order to provide the internal context of Node to resolve all variables and dependencies, I used the `node --expose-internals` flag as described [here](https://stackoverflow.com/questions/56436540/is-it-possible-to-debug-node-internal-modules). But I ended up at `ReferenceError: internalBinding is not defined`.

**Comment by ValYouW** [comment]
Great!
BTW, one time I wanted to understand something in node so I just compiled it from source and debugged it (the c++ code). So you can always clone "node", modify the "libs" as you want and compile, you will have your own modified version of the libs....
Send a link to the paper when you are done with your project :)

**Comment by christophschw** [comment]
Yes, this is a very good idea.
Unfortunately, the overall report will be in German, but at least the abstract will be translated. I secretly hope that maybe my professor or someone at the chair will take the results publish it in english 😉 I'll keep you posted 😊 
Thanks again!
