### ISSUE TITLE
Problem with tracing node_modules

### ISSUE THREAD

**Issue by Arklaide** [ValYouW/njsTrace#22]
Hi,
I have a problem trying to make njsTrace include the files inside of the node_modules folder. I have tried giving inject the following parameters: 
`   var njstrace = require('njstrace').inject({
        files: ["**/*.js"],
        formatter: new TSVFormatter()
    });`
Which should include all .js files; I also tried to include `'**/node_modules/**` in the files array. This should override the default negation and even when removing the default negation - it still does not work with the files inside of node_modules; only my own files are being traced.

I would love to continue with njsTrace as part of bachelor project, so do you have any idea of why this does not work?

**Comment by ValYouW** [comment]
Hi, I can't reproduce...
Here is my test app:

**server.js**
```js
var njstrace = require('njstrace');
njstrace.inject({
	enabled: true,
	inspectArgs: false,
	files: '**/*.js'
});

var app = require('./app.js');
```

**app.js**
```js
var express = require('express');

var app = express();
app.get('/', function getSlash(req, res) {
	res.send('Hi there!');
});

app.listen(3000, function onListen() {
	console.log('App listening on 3000');
});
```

My folder structure:
```
/d/temp/njtest/server.js
/d/temp/njtest/app.js
/d/temp/njtest/node_modules/...
```
Then running from `/d/temp/njtest`
```
node server.js
```
I get tracing on all the files, including node_modules.

Tested both on windows and WSL... try my simple example above, is it working for you?

**Comment by Arklaide** [comment]
Hi,
Thanks for the reply. We got it working, sorry for not updating the issue.
We tried a different project, where it worked. Still unsure why it did not work on our first test project, but that is in the past now.
Thank you for your time!
