### ISSUE TITLE
Tracing vm Script

### ISSUE THREAD

**Issue by zek** [ValYouW/njsTrace#28]
Hello, I'm  trying to trace vm.Script which is executed in a custom vm context. 

Do you know any workaround to trace it?

```js
import jsdom from "jsdom";
import vm from "vm";
import fs from "fs";

const dom = new jsdom.JSDOM(``)

const test = new vm.Script(fs.readFileSync('./mymod.js', 'utf-8'));
test.runInContext(dom.getInternalVMContext())
```

**Comment by ValYouW** [comment]
Never tried but I dont see a reason why it should not work if mymod.js has the tracing enabled...
