### ISSUE TITLE
Tracing code execution of an Angular 2+/TypeScript/JavaScript application

### ISSUE THREAD

**Issue by ar-IGT** [ValYouW/njsTrace#29]
If I understand correctly, the process of tracing Angular/TS/JS code executed in browser, while running app, isn't possible for njsTrace, because the code generated by Angular Dev Server (based on Webpack) is ESM, not CommonJS?
It's UI app not backend, native Node.js scripts, so it may not work, I guess?

**Comment by ValYouW** [comment]
Correct, as the names suggests this lib is for tracing code executed by nodejs
