### ISSUE TITLE
Not working with generators

### ISSUE THREAD

**Issue by aa6** [ValYouW/njsTrace#8]
Hello. I've fell into troubles using `njsTrace` with generators. If I remove the asterisk symbol from `mymod.js` or launch it with node directly, everything compiles fine.

main.js:

``` javascript
var njstrace = require('njstrace').inject(),
    mymod = require('./mymod.js');

// Use only 4 digits so the output would be easier to read
mymod.run();
```

mymod.js

``` javascript
exports.run = function() {
    var test = function*(){}
    console.log(123)
}
```

Output:

``` console
$ node main.js 
/home/me/tst/insp/main.js:5
mymod.run();
      ^

TypeError: mymod.run is not a function
    at Object.<anonymous> (/home/me/tst/insp/main.js:5:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

**Comment by ValYouW** [comment]
This project is very old, I don't think it would work with ES6. I don't have time for testing, but maybe updating the "falafel" dependency could help (as it might use more recent version of esprima that understands ES6).

**Comment by aa6** [comment]
I've updated falafel to `1.2.0` and just in case deleted all other versions of falafel but it doesn't seems that something has changed, it still throws an exception about an "Unexpected token (3:23)". Anyway, thanks for the module you've done, it's great. Will try my luck with debugging that falafel thing.

**Comment by ValYouW** [comment]
Well, that's a progress I guess.. :)

**Comment by aa6** [comment]
Wow, that was a waste of time. All I really had to do is to change the acorn options to `{ranges: true, locations: true, ecmaVersion: 6}` after updating the falafel. And also to add esprima to dependencies as they drop it. I guess I'll make a pull request but still not sure if this will break anything. Anyway at least it might help you if you would ever want to update this project.

**Comment by ValYouW** [comment]
@aa6 Thanks! Hmm, so you say they dropped esprima? I wonder what they use though...

**Comment by ValYouW** [comment]
Should be working now after upgrading falafel
